### ISSUE TITLE
2 bugs

### ISSUE THREAD

**Issue by 17jrouso** [matheussampaio/dota-quiz#1]
I have -1 guesses, and for mana treads it only gave me boots and gloves, the belt was missing, so I put in a robe and it accepted it.

**Comment by matheussampaio** [comment]
We have three different kind of threads: `Agi`, `Str` and `Int`. You should use `Band of Elvenskin`, `Belt of Strength` and `Robe of the Magi` respectively.

**Comment by matheussampaio** [comment]
Hi, I add a better bug report. If you find yourself with -1 guesses again, please create a new report.

Thank you!
